export type Language = 'en' | 'ar' | 'ckb' | 'kmr';

export interface TranslationDict {
  [key: string]: string | { [key: string]: string };
}

const translations: Record<Language, TranslationDict> = {
  en: {
    app: { title: 'MedLab Pro', subtitle: 'Complete Laboratory Management System' },
    nav: { dashboard: 'Dashboard', patients: 'Patients', tests: 'Tests', results: 'Results', pricing: 'Pricing & Packages', packages: 'Test Packages', reports: 'Reports', news: 'News & Offers', settings: 'Settings', logout: 'Logout' },
    dashboard: { welcome: 'Welcome to MedLab Pro', stats: 'Overview Statistics', totalPatients: 'Total Patients', totalTests: 'Total Tests', completedTests: 'Completed', pendingTests: 'Pending', revenue: 'Revenue', expenses: 'Expenses', netProfit: 'Net Profit', completionRate: 'Completion Rate', monthlyStats: 'Monthly Statistics', quickActions: 'Quick Actions', newPatient: 'New Patient', newTest: 'New Test', viewReports: 'View Reports', exportData: 'Export Data' },
    patients: { title: 'Patients', addNew: 'Add Patient', search: 'Search patients...', firstName: 'First Name', lastName: 'Last Name', email: 'Email', phone: 'Phone', gender: 'Gender', dateOfBirth: 'Date of Birth', actions: 'Actions', noResults: 'No patients found' },
    tests: { title: 'Lab Tests', addNew: 'New Test', status: 'Status', priority: 'Priority', category: 'Category', price: 'Price', testName: 'Test Name', patient: 'Patient', orderedDate: 'Ordered Date', noResults: 'No tests found' },
    results: { title: 'Test Results', addNew: 'Add Result', verify: 'Verify', parameters: 'Parameters', summary: 'Summary', interpretation: 'Interpretation', normal: 'Normal', abnormal: 'Abnormal', pdf: 'Download PDF' },
    pricing: { title: 'Pricing & Packages', addItem: 'Add Price Item', addPackage: 'Add Package', name: 'Name', category: 'Category', price: 'Price', costPrice: 'Cost Price', packagePrice: 'Package Price', savings: 'You Save', tests: 'Tests', highlights: 'Highlights', badge: 'Badge', active: 'Active', inactive: 'Inactive', activePackages: 'Active Packages', perTest: 'per test', discount: 'Discount', originalPrice: 'Original Price', packageDiscount: 'Package Discount' },
    reports: { title: 'Reports & Analytics', financial: 'Financial Report', patientStats: 'Patient Statistics', testCategories: 'Test Categories', export: 'Export', exportPatients: 'Export Patients CSV', exportTests: 'Export Tests CSV', exportPayments: 'Export Payments CSV', exportIncomeOutcome: 'Export Income/Outcome CSV', subscribeEmail: 'Subscribe to Email Reports', email: 'Email Address', frequency: 'Frequency', daily: 'Daily', weekly: 'Weekly', subscribe: 'Subscribe', unsubscribe: 'Unsubscribe', incomeVsExpenses: 'Income vs Expenses', period: 'Period', totalIncome: 'Total Income', totalOutcome: 'Total Outcome', netBalance: 'Net Balance' },
    news: { title: 'News & Offers', addNew: 'Add News', featured: 'Featured', category: 'Category', publishDate: 'Publish Date', general: 'General', offer: 'Offer', update: 'Update', healthTip: 'Health Tip', noNews: 'No news articles yet' },
    offers: { title: 'Offers & Discounts', couponCode: 'Coupon Code', discountPercentage: 'Discount %', validFrom: 'Valid From', validUntil: 'Valid Until', maxDiscount: 'Max Discount', minPurchase: 'Min Purchase', isActive: 'Active', applicableTests: 'Applicable Tests' },
    common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', search: 'Search', filter: 'Filter', loading: 'Loading...', error: 'Error', success: 'Success', confirm: 'Confirm', back: 'Back', next: 'Next', previous: 'Previous', noData: 'No data available', actions: 'Actions', status: 'Status', createdAt: 'Created', updatedAt: 'Updated', langEn: 'English', langAr: 'العربية', langCkb: 'کوردی سۆرانی', langKmr: 'کورمانجی' },
    subscribe: { title: 'Subscribe to Daily Reports', description: 'Get daily email reports with lab statistics, income, and expenses', email: 'Email Address', frequency: 'Frequency', daily: 'Daily', weekly: 'Weekly', subscribe: 'Subscribe', success: 'Subscribed successfully!', unsubscribe: 'Unsubscribe' },
    packages: { title: 'Test Packages', popular: 'Popular', bestValue: 'Best Value', saving: 'Save {percent}%', includes: 'Includes', perPackage: 'per package', originalTotal: 'Original Total', packagePrice: 'Package Price', buyNow: 'Book Now', viewDetails: 'View Details', noPackages: 'No packages available' },
  },
  ar: {
    app: { title: 'ميدلاب برو', subtitle: 'نظام إدارة المختبرات المتكامل' },
    nav: { dashboard: 'لوحة التحكم', patients: 'المرضى', tests: 'الفحوصات', results: 'النتائج', pricing: 'الأسعار والباقات', packages: 'باقات الفحوصات', reports: 'التقارير', news: 'الأخبار والعروض', settings: 'الإعدادات', logout: 'تسجيل الخروج' },
    dashboard: { welcome: 'مرحباً بك في ميدلاب برو', stats: 'إحصائيات عامة', totalPatients: 'إجمالي المرضى', totalTests: 'إجمالي الفحوصات', completedTests: 'مكتملة', pendingTests: 'معلقة', revenue: 'الإيرادات', expenses: 'المصروفات', netProfit: 'صافي الربح', completionRate: 'نسبة الإنجاز', monthlyStats: 'الإحصائيات الشهرية', quickActions: 'إجراءات سريعة', newPatient: 'مريض جديد', newTest: 'فحص جديد', viewReports: 'عرض التقارير', exportData: 'تصدير البيانات' },
    patients: { title: 'المرضى', addNew: 'إضافة مريض', search: 'بحث عن مرضى...', firstName: 'الاسم الأول', lastName: 'اسم العائلة', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', gender: 'الجنس', dateOfBirth: 'تاريخ الميلاد', actions: 'إجراءات', noResults: 'لم يتم العثور على مرضى' },
    tests: { title: 'الفحوصات المخبرية', addNew: 'فحص جديد', status: 'الحالة', priority: 'الأولوية', category: 'التصنيف', price: 'السعر', testName: 'اسم الفحص', patient: 'المريض', orderedDate: 'تاريخ الطلب', noResults: 'لم يتم العثور على فحوصات' },
    results: { title: 'نتائج الفحوصات', addNew: 'إضافة نتيجة', verify: 'تحقق', parameters: 'المعايير', summary: 'ملخص', interpretation: 'تفسير', normal: 'طبيعي', abnormal: 'غير طبيعي', pdf: 'تحميل PDF' },
    pricing: { title: 'الأسعار والباقات', addItem: 'إضافة عنصر سعر', addPackage: 'إضافة باقة', name: 'الاسم', category: 'التصنيف', price: 'السعر', costPrice: 'سعر التكلفة', packagePrice: 'سعر الباقة', savings: 'وفرت', tests: 'فحوصات', highlights: 'أبرز المزايا', badge: 'شارة', active: 'نشط', inactive: 'غير نشط', activePackages: 'الباقات النشطة', perTest: 'لكل فحص', discount: 'خصم', originalPrice: 'السعر الأصلي', packageDiscount: 'خصم الباقة' },
    reports: { title: 'التقارير والتحليلات', financial: 'التقرير المالي', patientStats: 'إحصائيات المرضى', testCategories: 'تصنيفات الفحوصات', export: 'تصدير', exportPatients: 'تصدير المرضى CSV', exportTests: 'تصدير الفحوصات CSV', exportPayments: 'تصدير المدفوعات CSV', exportIncomeOutcome: 'تصدير الإيرادات/المصروفات CSV', subscribeEmail: 'الاشتراك في التقارير البريدية', email: 'البريد الإلكتروني', frequency: 'التكرار', daily: 'يومي', weekly: 'أسبوعي', subscribe: 'اشتراك', unsubscribe: 'إلغاء الاشتراك', incomeVsExpenses: 'الإيرادات مقابل المصروفات', period: 'الفترة', totalIncome: 'إجمالي الإيرادات', totalOutcome: 'إجمالي المصروفات', netBalance: 'صافي الرصيد' },
    news: { title: 'الأخبار والعروض', addNew: 'إضافة خبر', featured: 'مميز', category: 'التصنيف', publishDate: 'تاريخ النشر', general: 'عام', offer: 'عرض', update: 'تحديث', healthTip: 'نصيحة صحية', noNews: 'لا توجد أخبار بعد' },
    offers: { title: 'العروض والخصومات', couponCode: 'رمز الكوبون', discountPercentage: 'نسبة الخصم %', validFrom: 'صالح من', validUntil: 'صالح حتى', maxDiscount: 'أقصى خصم', minPurchase: 'أقل مشتريات', isActive: 'نشط', applicableTests: 'الفحوصات المطبقة' },
    common: { save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', search: 'بحث', filter: 'تصفية', loading: 'جارٍ التحميل...', error: 'خطأ', success: 'نجاح', confirm: 'تأكيد', back: 'رجوع', next: 'التالي', previous: 'السابق', noData: 'لا توجد بيانات', actions: 'إجراءات', status: 'الحالة', createdAt: 'تاريخ الإنشاء', updatedAt: 'آخر تحديث', langEn: 'English', langAr: 'العربية', langCkb: 'کوردی سۆرانی', langKmr: 'کورمانجی' },
    subscribe: { title: 'اشترك في التقارير اليومية', description: 'احصل على تقارير يومية عبر البريد الإلكتروني مع إحصائيات المختبر والإيرادات والمصروفات', email: 'البريد الإلكتروني', frequency: 'التكرار', daily: 'يومي', weekly: 'أسبوعي', subscribe: 'اشتراك', success: 'تم الاشتراك بنجاح!', unsubscribe: 'إلغاء الاشتراك' },
    packages: { title: 'باقات الفحوصات', popular: 'الأكثر طلباً', bestValue: 'أفضل قيمة', saving: 'وفر {percent}%', includes: 'يشمل', perPackage: 'للباقة', originalTotal: 'المجموع الأصلي', packagePrice: 'سعر الباقة', buyNow: 'احجز الآن', viewDetails: 'عرض التفاصيل', noPackages: 'لا توجد باقات متاحة' },
  },
  ckb: {
    app: { title: 'مێدلاب پرۆ', subtitle: 'سیستەمی بەڕێوەبردنی تەواوی تاقیگە' },
    nav: { dashboard: 'داشبۆرد', patients: 'نەخۆشەکان', tests: 'پشکنینەکان', results: 'ئەنجامەکان', pricing: 'نرخ و پاکێجەکان', packages: 'پاکێجی پشکنین', reports: 'ڕاپۆرتەکان', news: 'هەواڵ و پێشکەشکراوەکان', settings: 'ڕێکخستنەکان', logout: 'چوونە دەرەوە' },
    dashboard: { welcome: 'بەخێربێیت بۆ مێدلاب پرۆ', stats: 'ئاماری گشتی', totalPatients: 'کۆی نەخۆشەکان', totalTests: 'کۆی پشکنینەکان', completedTests: 'تەواوکراوەکان', pendingTests: 'چاوەڕوانەکان', revenue: 'داھات', expenses: 'خەرجییەکان', netProfit: 'قازانجی تۆڕ', completionRate: 'ڕێژەی تەواوبوون', monthlyStats: 'ئاماری مانگانە', quickActions: 'کردەوەی خێرا', newPatient: 'نەخۆشی نوێ', newTest: 'پشکنینی نوێ', viewReports: 'بینینی ڕاپۆرتەکان', exportData: 'هەناردنی داتا' },
    patients: { title: 'نەخۆشەکان', addNew: 'زیادکردنی نەخۆش', search: 'گەڕان بەدوای نەخۆش...', firstName: 'ناوی یەکەم', lastName: 'نازناو', email: 'ئیمەیڵ', phone: 'ژمارەی تەلەفۆن', gender: 'ڕەگەز', dateOfBirth: 'ڕێکەوتی لەدایکبوون', actions: 'کردەوەکان', noResults: 'هیچ نەخۆشێک نەدۆزرایەوە' },
    tests: { title: 'پشکنینەکانی تاقیگە', addNew: 'پشکنینی نوێ', status: 'باری دۆخ', priority: 'پێشینە', category: 'پۆل', price: 'نرخ', testName: 'ناوی پشکنین', patient: 'نەخۆش', orderedDate: 'ڕێکەوتی داواکردن', noResults: 'هیچ پشکنینێک نەدۆزرایەوە' },
    results: { title: 'ئەنجامەکانی پشکنین', addNew: 'زیادکردنی ئەنجام', verify: 'پشتراستکردنەوە', parameters: 'پارامیتەرەکان', summary: 'پوختە', interpretation: 'لێکدانەوە', normal: 'ئاسایی', abnormal: 'نائاسایی', pdf: 'داگرتنی PDF' },
    pricing: { title: 'نرخ و پاکێجەکان', addItem: 'زیادکردنی بڕگەی نرخ', addPackage: 'زیادکردنی پاکێج', name: 'ناو', category: 'پۆل', price: 'نرخ', costPrice: 'نرخی تێچوون', packagePrice: 'نرخی پاکێج', savings: 'پاشەکەوتت کرد', tests: 'پشکنینەکان', highlights: 'خاڵە گرنگەکان', badge: 'نیشانە', active: 'چالاک', inactive: 'ناچالاک', activePackages: 'پاکێجە چالاکەکان', perTest: 'بۆ هەر پشکنینێک', discount: 'داشکاندن', originalPrice: 'نرخی سەرەکی', packageDiscount: 'داشکاندنی پاکێج' },
    reports: { title: 'ڕاپۆرت و شیکاری', financial: 'ڕاپۆرتی دارایی', patientStats: 'ئاماری نەخۆشەکان', testCategories: 'پۆلەکانی پشکنین', export: 'هەناردن', exportPatients: 'هەناردنی نەخۆشەکان CSV', exportTests: 'هەناردنی پشکنینەکان CSV', exportPayments: 'هەناردنی پارەدانەکان CSV', exportIncomeOutcome: 'هەناردنی داھات/خەرجی CSV', subscribeEmail: 'بەشداربوون لە ڕاپۆرتی ئیمەیڵ', email: 'ناونیشانی ئیمەیڵ', frequency: 'چەند جارێک', daily: 'ڕۆژانە', weekly: 'هەفتانە', subscribe: 'بەشداربوون', unsubscribe: 'پاشگەزبوونەوە', incomeVsExpenses: 'داھات بەرامبەر خەرجی', period: 'ماوە', totalIncome: 'کۆی داھات', totalOutcome: 'کۆی خەرجی', netBalance: 'بڕی تۆڕ' },
    news: { title: 'هەواڵ و پێشکەشکراوەکان', addNew: 'زیادکردنی هەواڵ', featured: 'پێشکەوتوو', category: 'پۆل', publishDate: 'ڕێکەوتی بڵاوکردنەوە', general: 'گشتی', offer: 'پێشکەشکراو', update: 'نوێکردنەوە', healthTip: 'ڕێنمایی تەندروستی', noNews: 'هیچ هەواڵێک نییە' },
    offers: { title: 'پێشکەشکراو و داشکاندنەکان', couponCode: 'کۆدی کۆپۆن', discountPercentage: 'ڕێژەی داشکاندن %', validFrom: 'لە', validUntil: 'هەتا', maxDiscount: 'زۆرترین داشکاندن', minPurchase: 'کەمترین کڕین', isActive: 'چالاک', applicableTests: 'پشکنینە جێبەجێکراوەکان' },
    common: { save: 'پاشەکەوت', cancel: 'ڕەتکردنەوە', delete: 'سڕینەوە', edit: 'دەستکاری', search: 'گەڕان', filter: 'پاڵاوتن', loading: 'بارکردن...', error: 'هەڵە', success: 'سەرکەوتن', confirm: 'پشتڕاستکردنەوە', back: 'گەڕانەوە', next: 'دواتر', previous: 'پێشتر', noData: 'هیچ داتایەک نییە', actions: 'کردەوەکان', status: 'باری دۆخ', createdAt: 'ڕێکەوتی دروستکردن', updatedAt: 'دوایین نوێکردنەوە', langEn: 'English', langAr: 'العربية', langCkb: 'کوردی سۆرانی', langKmr: 'کورمانجی' },
    subscribe: { title: 'بەشداربە لە ڕاپۆرتی ڕۆژانە', description: 'ڕاپۆرتی ڕۆژانەی ئیمەیڵ وەربگرە لەگەڵ ئاماری تاقیگە و داھات و خەرجییەکان', email: 'ناونیشانی ئیمەیڵ', frequency: 'چەند جارێک', daily: 'ڕۆژانە', weekly: 'هەفتانە', subscribe: 'بەشداربوون', success: 'بە سەرکەوتوویی بەشداربوویت!', unsubscribe: 'پاشگەزبوونەوە' },
    packages: { title: 'پاکێجی پشکنین', popular: 'بەناوبانگ', bestValue: 'باشترین نرخ', saving: '{percent}% پاشەکەوت', includes: 'لەخۆدەگرێت', perPackage: 'بۆ هەر پاکێجێک', originalTotal: 'کۆی سەرەکی', packagePrice: 'نرخی پاکێج', buyNow: 'ئێستا بگەرە', viewDetails: 'بینینی وردەکاری', noPackages: 'هیچ پاکێجێک نییە' },
  },
  kmr: {
    app: { title: 'MedLab Pro', subtitle: 'Sîstema Birêvebirina Tevahiya Laboratûwarê' },
    nav: { dashboard: 'Dashboard', patients: 'Nexweş', tests: 'Test', results: 'Encam', pricing: 'Biha & Pakêt', packages: 'Pakêtên Testê', reports: 'Rapor', news: 'Nûçe & Pêşkêşî', settings: 'Eyar', logout: 'Derkeve' },
    dashboard: { welcome: 'Bi xêr hatî MedLab Pro', stats: 'Statîstîkên Giştî', totalPatients: 'Tevahiya Nexweşan', totalTests: 'Tevahiya Testan', completedTests: 'Qediyayî', pendingTests: 'Li Bendê', revenue: 'Dahat', expenses: 'Mesref', netProfit: 'Qazanca Safî', completionRate: 'Rêjeya Qedandinê', monthlyStats: 'Statîstîkên Mehane', quickActions: 'Çalakiyên Lezgîn', newPatient: 'Nexweşê Nû', newTest: 'Testa Nû', viewReports: 'Raporan Bibîne', exportData: 'Daneyan Derxîne' },
    patients: { title: 'Nexweş', addNew: 'Nexweşekî Zêde Bike', search: 'Nexweşan bigere...', firstName: 'Nav', lastName: 'Paşnav', email: 'E-name', phone: 'Telefon', gender: 'Zayend', dateOfBirth: 'Dîroka Jidayikbûnê', actions: 'Çalakî', noResults: 'Nexweş nehatin dîtin' },
    tests: { title: 'Testên Laboratûwarê', addNew: 'Testa Nû', status: 'Rewş', priority: 'Pêşînî', category: 'Kategorî', price: 'Biha', testName: 'Navê Testê', patient: 'Nexweş', orderedDate: 'Dîroka Fermanê', noResults: 'Test nehatin dîtin' },
    results: { title: 'Encamên Testê', addNew: 'Encamekê Zêde Bike', verify: 'Tesdîq Bike', parameters: 'Parametre', summary: 'Kurte', interpretation: 'Şîrove', normal: 'Normal', abnormal: 'Anormal', pdf: 'PDFê Daxîne' },
    pricing: { title: 'Biha & Pakêt', addItem: 'Tiştekî Bihayê Zêde Bike', addPackage: 'Pakêtekê Zêde Bike', name: 'Nav', category: 'Kategorî', price: 'Biha', costPrice: 'Bihayê Mesrefê', packagePrice: 'Bihayê Pakêtê', savings: 'Tu Teserûf Dikî', tests: 'Test', highlights: 'Ronahî', badge: 'Nîşan', active: 'Çalak', inactive: 'Neçalak', activePackages: 'Pakêtên Çalak', perTest: 'ji bo her testê', discount: 'Daxistin', originalPrice: 'Bihayê Resen', packageDiscount: 'Daxistina Pakêtê' },
    reports: { title: 'Rapor & Analîz', financial: 'Rapora Darayî', patientStats: 'Statîstîkên Nexweşan', testCategories: 'Kategoriyên Testê', export: 'Derxîne', exportPatients: 'Nexweşan Derxîne CSV', exportTests: 'Testan Derxîne CSV', exportPayments: 'Derdanî Derxîne CSV', exportIncomeOutcome: 'Dahat/Mesref Derxîne CSV', subscribeEmail: 'Bibe Aboneyê Raporên E-nameyê', email: 'Navnîşana E-nameyê', frequency: 'Pirbûn', daily: 'Rojane', weekly: 'Hefteyî', subscribe: 'Bibe Abone', unsubscribe: 'Abonetiyê Betal Bike', incomeVsExpenses: 'Dahat li hember Mesref', period: 'Serdem', totalIncome: 'Tevahiya Dahatê', totalOutcome: 'Tevahiya Mesrefê', netBalance: 'Bilança Safî' },
    news: { title: 'Nûçe & Pêşkêşî', addNew: 'Nûçeyekê Zêde Bike', featured: 'Taybet', category: 'Kategorî', publishDate: 'Dîroka Weşanê', general: 'Giştî', offer: 'Pêşkêşî', update: 'Nûkirin', healthTip: 'Şîreta Tenduristiyê', noNews: 'Nûçe tune ne' },
    offers: { title: 'Pêşkêşî & Daxistin', couponCode: 'Koda Kuponê', discountPercentage: 'Rêjeya Daxistinê %', validFrom: 'Ji', validUntil: 'Heta', maxDiscount: 'Daxistina Herî Zêde', minPurchase: 'Kirîna Herî Kêm', isActive: 'Çalak', applicableTests: 'Testên Bikêrhatî' },
    common: { save: 'Tomar Bike', cancel: 'Betal Bike', delete: 'Jê Bibe', edit: 'Sererast Bike', search: 'Bigere', filter: 'Fîltre', loading: 'Tê Barkirin...', error: 'Çewtî', success: 'Serkeftin', confirm: 'Tesdîq Bike', back: 'Vegere', next: 'Pêşve', previous: 'Bere', noData: 'Daneyên berdest nînin', actions: 'Çalakî', status: 'Rewş', createdAt: 'Dîroka Çêkirinê', updatedAt: 'Rojanekirina Dawî', langEn: 'English', langAr: 'العربية', langCkb: 'کوردی سۆرانی', langKmr: 'Kurmancî' },
    subscribe: { title: 'Bibe Aboneyê Raporên Rojane', description: 'Raporên e-nameyê yên rojane bi statîstîkên laboratûwarê, dahat û mesrefan bistîne', email: 'Navnîşana E-nameyê', frequency: 'Pirbûn', daily: 'Rojane', weekly: 'Hefteyî', subscribe: 'Bibe Abone', success: 'Bi serkeftinî bû abone!', unsubscribe: 'Abonetiyê Betal Bike' },
    packages: { title: 'Pakêtên Testê', popular: 'Populer', bestValue: 'Qedrê Herî Baş', saving: '{percent}% Teserûf', includes: 'Tê de ye', perPackage: 'ji bo pakêtê', originalTotal: 'Tevahiya Resen', packagePrice: 'Bihayê Pakêtê', buyNow: 'Niha Veqetîne', viewDetails: 'Detayan Bibîne', noPackages: 'Pakêt tune ne' },
  },
};

export default translations;